### ISSUE TITLE
evaluate的运行出错

### ISSUE THREAD

**Issue by irisgloria** [zhulf0804/PointPillars#25]
你好，我输入以下代码测试evaluate
`python evaluate.py --ckpt pretrained/epoch_160.pth --data_root kittiCut`
出现了下列错误
```
Traceback (most recent call last):
  File "E:\LCH_Content\Code\1Preparations\PointPillars__zhulf0804\evaluate.py", line 386, in <module>
    main(args)
  File "E:\LCH_Content\Code\1Preparations\PointPillars__zhulf0804\evaluate.py", line 280, in main
    val_dataset = Kitti(data_root=args.data_root,
  File "E:\LCH_Content\Code\1Preparations\PointPillars__zhulf0804\dataset\kitti.py", line 50, in __init__
    self.sorted_ids = list(self.data_infos.keys())
AttributeError: 'list' object has no attribute 'keys'
```
请问是我的输入有问题吗，搜问题得到的解决方案，都不太行

**Comment by zhulf0804** [comment]
看着像是输入有问题，请问您的kittiCut是怎么产生的呢
