### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'convert_from_pinhole_camera_parameters'

### ISSUE THREAD

**Issue by Leonnn12138** [zhulf0804/PointPillars#64]
please help

Traceback (most recent call last):
  File "test.py", line 138, in <module>
    main(args)
  File "test.py", line 87, in main
    vis_pc(pc, bboxes=lidar_bboxes, labels=labels)
  File "/mnt/PointPillars/utils/vis_o3d.py", line 97, in vis_pc
    vis_core(vis_objs)
  File "/mnt/PointPillars/utils/vis_o3d.py", line 59, in vis_core
    ctr.convert_from_pinhole_camera_parameters(param)
AttributeError: 'NoneType' object has no attribute 'convert_from_pinhole_camera_parameters'

**Comment by ronkkkk** [comment]
I have the same problem and I don't know how to solve it

**Comment by ABBoyangCD** [comment]
I have the same problem too!
我也有相同的问题！

**Comment by farhadi76m** [comment]
> please help
> 
> Traceback (most recent call last): File "test.py", line 138, in main(args) File "test.py", line 87, in main vis_pc(pc, bboxes=lidar_bboxes, labels=labels) File "/mnt/PointPillars/utils/vis_o3d.py", line 97, in vis_pc vis_core(vis_objs) File "/mnt/PointPillars/utils/vis_o3d.py", line 59, in vis_core ctr.convert_from_pinhole_camera_parameters(param) AttributeError: 'NoneType' object has no attribute 'convert_from_pinhole_camera_parameters'

Did you solve it ?!

**Comment by Windson9** [comment]
@farhadi76m did you solve it ? :D

**Comment by ShuaibZyx** [comment]
Try open3d==0.16.0

**Comment by quanquan-qq** [comment]
> Try open3d==0.16.0

没有用

**Comment by rhnabil** [comment]
Anyone solved it?

@Leonnn12138 @zhulf0804

**Comment by michelgokan** [comment]
I'm not sure if this is going to help but if you are running via a docker or apptainer, perhaps pass `--env DISPLAY=$DISPLAY` as a parameter when running exec command.

**Comment by GaneshAdam** [comment]
I faced similar issue.
Commenting line "vis_pc(pc, bboxes=lidar_bboxes, labels=labels)" from onnx_infer.py solved problem for me.
vis_pc includes visualisation code which tries to create window and I was working on remote system with just ssh login (no UI access)
